language: node_js
cache: yarn

notifications:
  email:
    on_success: never
    on_failure: always

node_js:
  - '8'

script:
  - yarn test -- --coverage
  - yarn build

deploy:
  provider: pages
  skip-clean: true
  github-token: f5b88529d304a71bdcf93c114e0686304b001587
  keep-history: true
  on:
    branch: master