language: node_js
cache: yarn

notifications:
  email:
    on_success: never
    on_failure: always

node_js:
  - '8'

script:
  - yarn test -- --coverage
  - git config user.name "teofpqy"
  - git config user.email "teofpqy@outlook.com"
  - yarn build
  - gh-pages -d build -r "https://${GH_token}@${GH_repo}"